// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/20/2026, 12:33:02 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/user/work/tattoo-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/work/tattoo-web/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/work/tattoo-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/work/tattoo-web/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/work/tattoo-web/app/plugins/**/*.{js,ts,mjs}","/Users/user/work/tattoo-web/app/composables/**/*.{js,ts,mjs}","/Users/user/work/tattoo-web/app/utils/**/*.{js,ts,mjs}","/Users/user/work/tattoo-web/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/work/tattoo-web/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/user/work/tattoo-web/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/user/work/tattoo-web/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;